version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
<<<<<<< HEAD
            echo $CIRCLE_WORKING_DIRECTORY
            sudo apt-get update && sudo apt-get install wget zip unzip -y
=======
          echo $CIRCLE_WORKING_DIRECTORY
          sudo apt-get update && sudo apt-get install wget zip unzip -y
>>>>>>> parent of 3e2fbda... final change
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
            unzip packer*.zip
            chmod +x packer
      - run:
          name: Validate Packer Template
          command: ./packer validate centos-ami-template.json
      - run:
          name: Build AMI
          command: ./packer build centos-ami-template.json
